name: AltitudeParticles
version: ${project.version}
main: com.alttd.AltitudeParticles
api-version: 1.18
commands:
  apart:
    permission: apart.use
    description: Handles all AltitudeParticles commands
    usage: /apart